config/routes.rb
Warranties::Application.routes.draw do
  devise_for :users

  resources :warranties do
    get 'crop', :on => :member
  end

  root :to => 'warranties#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  belongs_to :user
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :language

  has_many :warranties, :dependent => :destroy
  has_many :brands, :dependent => :destroy
end

app/models/warranty.rb
class Warranty < ActiveRecord::Base
  # CarrierWave
  mount_uploader :warranty, WarrantyUploader
  mount_uploader :photo, PhotoUploader

  # attributes
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  delegate :name, :to => :brand, :prefix => true, :allow_nil => true

  # relations
  belongs_to :brand
  belongs_to :user

  # validations
  validates :name, :warranty, :expires_on, :presence => true

  # callbacks
  before_save :set_brand_from_name # When brand_name is assigned to object, handle the brand attribute automatically.
  after_update :crop_photo

  def brand_name=(value)
    # Changes in brand_name are not tracked by the ActiveRecord::Dirty module,
    # so we do it ourselves.
    @brand_name_changed = true
    @brand_name = value
  end

  private
    def crop_photo
      photo.recreate_versions! if crop_x.present?
    end

    def set_brand_from_name
      return unless @brand_name_changed

      self.brand = @brand_name.present? ? user.brands.find_or_create_by_name(@brand_name) : nil
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  before_filter :set_locale

  private
  def set_locale
    locale = params[:locale] || current_user.try(:language) || "#{I18n.default_locale}"
    logger.debug "[#{self.class}.set_locale] Change locale to #{locale}."
    I18n.locale = locale
  end
end

app/controllers/warranties_controller.rb
class WarrantiesController < ApplicationController
  before_filter :find_warranty, :only => [:show, :edit, :update, :destroy]

  def index
    @search = current_user.warranties.search(params[:search])
    @warranties = @search.all
  end

  def new
    @warranty = Warranty.new
  end

  def show
  end

  def edit
  end

  def create
    @warranty = current_user.warranties.build(params[:warranty])
    if @warranty.save
      if params[:warranty][:photo]
        render :crop
      else
        redirect_to(warranty_path(@warranty), :notice => t('flash.warranty_created'))
      end
    else
      render :new
    end
  end

  def update
    if @warranty.update_attributes(params[:warranty])
      if params[:warranty][:photo]
        render :crop
      else
        redirect_to(warranty_path(@warranty), :notice => t('flash.warranty_updated'))
      end
    else
      render :edit
    end
  end

  def destroy
    @warranty.destroy
    redirect_to(warranties_path, :notice => t('flash.warranty_destroyed'))
  end

  private
    def find_warranty
      @warranty = current_user.warranties.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Transform into proper Twitter Bootstrap type
  # when displaying flash message.
  #   Usage:
  # - flash.each do |name, msg|
  #   .alert{ :class => "alert-#{twitterized_type(name)}" }
  #     %a.close{ 'data-dismiss' => "alert" } x
  #     = msg
  def twitterized_type(type)
    case type
      when :alert
        "warning"
      when :error
        "error"
      when :notice
        "info"
      when :success
        "success"
      else
        type.to_s
    end
  end

  def locale_selection
    existing_locale_names = I18n.available_locales.map(&:to_s)

    pairs = Locale::MAPPING.to_a.map(&:reverse).sort_by(&:first)
    pairs.select {|pair| existing_locale_names.include?(pair.last) }
  end
end

app/helpers/twitter_bootstrap_helper.rb
module TwitterBootstrapHelper

  # Returns structure for Twitter Bootstrap navbar surrounding the content
  # and uses +name+ for outer element.
  #
  # === Examples
  #   <%= tb_navbar do -%>
  #     Hello world!
  #   <% end -%>
  #   # => <div class="navbar">
  #          <div class="navbar-inner">
  #            <div class="container">
  #              Hello world!
  #            </div>
  #          </div>
  #        </div>
  #
  #   <%= tb_navbar(:nav) do -%>
  #     Hello world!
  #   <% end -%>
  #   # => <nav class="navbar">
  #          <div class="navbar-inner">
  #            <div class="container">
  #              Hello world!
  #            </div>
  #          </div>
  #        </nav>
  def tb_navbar(name = :div, options = {})
    default_options = {:class => 'navbar'}
    options = options.merge(default_options)

    content_tag(name, options) do
      content_tag(:div, :class => 'navbar-inner') do
        content_tag(:div, '', :class => 'container') do
          yield if block_given?
        end
      end
    end
  end

  # Returns structure for Twitter Bootstrap popover with +content+ used as content for the popup.
  #
  # @param [String] content Text that's visible when the popup shows up.
  #   +simple_format+ is used to add P- and BR-tags. Long text is truncated after appr. 800 characters.
  # @param [Hash] opts Set of options to configure the popup:
  # @option opts [Symbol, String] :tag HTML tag used as wrapped (default :div)
  # @option opts [String] :title Title for the popover
  # @option opts [String] :class CSS classname used for +tag+
  #
  # @return [String] HTML to use in your view
  #
  # === Examples
  #   tb_popover("Hello world!")
  #   # <div data-content="<p>Hello world!</p>" rel="popover"></div>
  #
  #   tb_popover("Hello world!", :title => "Important!", :tag => 'i', :class => 'icon-info-sign')
  #   # <i class="icon-info-sign" data-content="<p>Hello world!</p>" rel="popover" data-original-title="Important!"></i>
  #
  def tb_popover(content, opts = {})
    tag = opts[:tag] || :div
    content = simple_format(escape_once(truncate(content, :length => 800)))
    options = {
      :class => opts[:class],
      :rel => 'popover',
      :title => opts[:title],
      :data => { :content => content }
    }

    content_tag(tag, options) {}
  end
end

app/helpers/warranties_helper.rb
module WarrantiesHelper
end

app/views/application/_flashes.html.haml
- flash.each do |name, msg|
  .alert{ :class => "alert-#{twitterized_type(name)}" }
    %a.close{ 'data-dismiss' => "alert" } x
    = msg

app/views/application/_side.html.haml
%aside
  %nav.side-nav
    %ul
      %li.nav-header= Warranty.model_name.human(:count => 2)
      %li= link_to t('text.title_warranties_path'), warranties_path
      %li= link_to t('text.title_new_warranty_path'), new_warranty_path

app/views/layouts/application.html.haml
<!doctype html>
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = yield :javascripts
    = csrf_meta_tags
  %body{ :class => "#{ controller.controller_name }" }
    /[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    %header
      = link_to "Warranties", root_path, :class => "brand"
      %nav
        %ul
          %li.active= link_to t('text.title_warranties_path'), warranties_path
      %nav.nav.pull-right
        %li.divider-vertical
        %li= link_to t('text.title_destroy_user_session_path'), destroy_user_session_path, :method => :delete
      %p.navbar-text.pull-right
        = t('text.logged_in_as_foo.html', :current_user => link_to(current_user.email, edit_user_registration_path))

    %div{:role => "main"}
      %section
        = render "side"

        %section
          = render "flashes"
          = yield
    %footer

app/views/layouts/sign.html.haml
<!doctype html>
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ [if gt IE 8]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{ :class => "sign" }
    /[if lt IE 7] <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
    %header
    %div{:role => "main"}
      = render "flashes"
      = yield
    %footer

app/views/warranties/_action_bar.html.haml
= tb_navbar(:nav, :id => 'action-bar') do
  %ul.nav
    - unless action_name == 'index'
      %li
        = link_to warranties_path do
          = t('text.action_bar_back')
    - if action_name == 'show'
      %li
        = link_to edit_warranty_path(warranty) do
          %i.icon-edit.icon-white
          = t('text.action_bar_edit')

    - if local_assigns.has_key?(:warranty) && !warranty.new_record?
      %li
        =link_to(warranty.warranty_url(:large), :class => 'fancybox', :id => "warranty_warranty_#{warranty.id}") do
          %i.icon-zoom-in.icon-white
          = t('text.action_bar_view_warranty')
      %li
        = link_to warranty, :method => :delete, :confirm => "Are you sure?" do
          %i.icon-remove.icon-white
          = t('text.action_bar_destroy')

  - if action_name == 'index'
    = form_for @search, :html => { :class => 'navbar-search pull-right' } do |f|
      = f.search_field :name_or_notes_contains, :class => 'search-query', :placeholder => "Search"

app/views/warranties/_form.html.haml
= simple_form_for(warranty, :html => { :class => 'form-horizontal' }) do |f|
  %legend= t("warranties.#{action_name}.title")
  = f.input :name
  = f.input :expires_on, :as => :string, :input_html => { :class => 'datepicker' }
  = f.input :warranty
  = f.input :photo
  - if !warranty.new_record? && warranty.photo?
    = f.input :remove_photo, :as => :boolean
  = f.input :brand_name, :input_html => { :autocomplete => 'off', :data => { :provide => 'typeahead', :source => brand_names} }
  = f.input :purchased_on, :as => :string, :input_html => { :class => 'datepicker' }
  = f.input :notes

  .form-actions
    = f.submit :class => 'btn-primary'

app/views/warranties/_warranty.html.haml
%li[warranty]
  = link_to(image_tag(warranty.photo_url(:thumb)), warranty)
  .caption
    %h5
      = highlight(warranty.name, @search.search_attributes["name_or_notes_contains"])
      - if warranty.notes
        = tb_popover(highlight(warranty.notes, @search.search_attributes["name_or_notes_contains"]), :tag => :i, :title => Warranty.human_attribute_name("notes"), :class => 'icon-info-sign')
    %dl
      %dt= "#{Warranty.human_attribute_name("expires_on")}:"
      %dd= l(warranty.expires_on, :format => :default)
      - if warranty.brand_name
        %dt= "#{Warranty.human_attribute_name("brand_name")}:"
        %dd= warranty.brand_name
      - if warranty.purchased_on
        %dt= "#{Warranty.human_attribute_name("purchased_on")}:"
        %dd= l(warranty.purchased_on, :format => :default)
    %p
      = link_to t('text.action_edit'), edit_warranty_path(warranty), :class => 'btn'
      = link_to t('text.action_destroy'), warranty, :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-danger'

app/views/warranties/crop.html.haml
= simple_form_for @warranty do |f|
  %legend Crop Photo
  - %w[x y w h].each do |attribute|
    = f.hidden_field "crop_#{attribute}"

  = image_tag @warranty.photo_url(:large), id: "cropbox"
  .form-actions
    = f.submit "Crop", :class => 'btn-primary'

app/views/warranties/edit.html.haml
= render 'action_bar', :warranty => @warranty
= render 'form', :warranty => @warranty, :brand_names => current_user.brands.map(&:name)

app/views/warranties/index.html.haml
= render 'action_bar'
%ul.warranties= render @warranties

app/views/warranties/new.html.haml
= render 'action_bar', :warranty => @warranty
= render 'form', :warranty => @warranty, :brand_names => current_user.brands.map(&:name)

app/views/warranties/show.html.haml
= render 'action_bar', :warranty => @warranty


.page-header
  %h1= @warranty.name

%p= image_tag(@warranty.photo_url(:thumb)) if @warranty.photo?
%p
  %strong= "#{Warranty.human_attribute_name("expires_on")}:"
  = l(@warranty.expires_on, :format => :default)
- if @warranty.brand_name
  %p
    %strong= "#{Warranty.human_attribute_name("brand_name")}:"
    = @warranty.brand_name
- if @warranty.purchased_on
  %p
    %strong= "#{Warranty.human_attribute_name("purchased_on")}:"
    = l(@warranty.purchased_on, :format => :default)
- if @warranty.notes
  %p
    %strong= "#{Warranty.human_attribute_name("notes")}:"
    = sanitize(simple_format(@warranty.notes))